export const curatedPhrases = [
  // --- GREETINGS & SMALL TALK ---
  { en: "Hello, how are you doing today?", pt: "Olá, como você está hoje?" },
  { en: "It is really nice to finally meet you.", pt: "É muito bom finalmente conhecer você." },
  { en: "How has your day been so far?", pt: "Como tem sido o seu dia até agora?" },
  { en: "I am doing great, thank you for asking.", pt: "Estou ótimo, obrigado por perguntar." },
  { en: "What do you like to do in your free time?", pt: "O que você gosta de fazer no seu tempo livre?" },
  { en: "I am really looking forward to the weekend.", pt: "Estou muito ansioso para o fim de semana." },
  { en: "Did you have a good weekend?", pt: "Você teve um bom fim de semana?" },
  { en: "The weather is absolutely beautiful today.", pt: "O tempo está absolutamente lindo hoje." },
  { en: "It is supposed to rain tomorrow afternoon.", pt: "A previsão é de chuva para amanhã à tarde." },
  { en: "I completely agree with your point of view.", pt: "Eu concordo completamente com o seu ponto de vista." },
  { en: "That sounds like a really great idea.", pt: "Isso parece uma ótima ideia." },
  { en: "I am sorry, I didn't quite catch that.", pt: "Desculpe, eu não entendi bem isso." },
  { en: "Could you please repeat that a little slower?", pt: "Você poderia repetir um pouco mais devagar, por favor?" },
  { en: "Thank you so much for all your help.", pt: "Muito obrigado por toda a sua ajuda." },
  { en: "You are very welcome, anytime.", pt: "De nada, disponha." },
  { en: "Long time no see! How have you been?", pt: "Quanto tempo! Como você tem passado?" },
  { en: "What have you been up to lately?", pt: "O que você tem feito ultimamente?" },
  { en: "It has been a while since we last spoke.", pt: "Faz um tempo desde que nos falamos pela última vez." },
  { en: "How is your family doing?", pt: "Como está a sua família?" },
  { en: "Let's catch up sometime next week.", pt: "Vamos colocar o papo em dia na semana que vem." },
  { en: "Are you doing anything special this weekend?", pt: "Você vai fazer algo especial neste fim de semana?" },
  { en: "I really love your outfit today.", pt: "Eu adorei a sua roupa hoje." },
  { en: "That is so funny! I can't believe it.", pt: "Isso é tão engraçado! Não consigo acreditar." },
  { en: "I am not sure what you mean.", pt: "Não tenho certeza do que você quer dizer." },
  { en: "Could you explain that again?", pt: "Você poderia explicar isso de novo?" },
  { en: "Have a great rest of your day!", pt: "Tenha um ótimo resto de dia!" },
  { en: "See you later, take care of yourself.", pt: "Até mais, se cuide." },
  { en: "Cheers, have a good one!", pt: "Valeu, tenha um bom dia!" },
  { en: "Catch you in a bit", pt: "Te vejo daqui a pouco." },
  { en: "How have you been?", pt: "Como você tem passado?" },

  // --- TRAVEL & DIRECTIONS ---
  { en: "Excuse me, where is the nearest subway station?", pt: "Com licença, onde fica a estação de metrô mais próxima?" },
  { en: "How do I get to the airport from here?", pt: "Como faço para chegar ao aeroporto daqui?" },
  { en: "I need to buy a ticket to New York.", pt: "Preciso comprar uma passagem para Nova York." },
  { en: "What time does the next train leave?", pt: "A que horas sai o próximo trem?" },
  { en: "Is there a public restroom around here?", pt: "Tem algum banheiro público por aqui?" },
  { en: "I am looking for a pharmacy.", pt: "Estou procurando uma farmácia." },
  { en: "Could you show me where that is on the map?", pt: "Você poderia me mostrar onde é isso no mapa?" },
  { en: "How much does a taxi to the hotel cost?", pt: "Quanto custa um táxi até o hotel?" },
  { en: "I need to book a room for two nights.", pt: "Preciso reservar um quarto para duas noites." },
  { en: "What time is check-in and check-out?", pt: "A que horas é o check-in e o check-out?" },
  { en: "Can you help me carry my luggage?", pt: "Você pode me ajudar a carregar minha bagagem?" },
  { en: "My flight is delayed by two hours.", pt: "Meu voo está atrasado em duas horas." },
  { en: "Where is the baggage claim area?", pt: "Onde é a área de restituição de bagagem?" },
  { en: "Do I need to transfer to another terminal?", pt: "Preciso me transferir para outro terminal?" },
  { en: "Does this bus go to the city center?", pt: "Este ônibus vai para o centro da cidade?" },
  { en: "Could you tell me when to get off?", pt: "Você poderia me avisar quando eu devo descer?" },
  { en: "I think we might be lost.", pt: "Acho que podemos estar perdidos." },
  { en: "Can you point me in the right direction?", pt: "Você pode me apontar a direção certa?" },
  { en: "How far is it from here?", pt: "A que distância fica daqui?" },
  { en: "Is it within walking distance?", pt: "Dá para ir a pé?" },
  { en: "I would like to rent a car for three days.", pt: "Eu gostaria de alugar um carro por três dias." },
  { en: "Where can I find a currency exchange?", pt: "Onde posso encontrar uma casa de câmbio?" },
  { en: "Do you know a good place to buy souvenirs?", pt: "Você conhece um bom lugar para comprar lembrancinhas?" },
  { en: "I need a window seat, please.", pt: "Preciso de um assento na janela, por favor." },
  { en: "Can I bring this on the airplane?", pt: "Posso levar isso no avião?" },
  { en: "What gate does the flight leave from?", pt: "De qual portão o voo sai?" },
  { en: "The traffic is really bad today.", pt: "O trânsito está muito ruim hoje." },
  { en: "Our train has been cancelled", pt: "Nosso trem foi cancelado." },

  // --- RESTAURANT & FOOD ---
  { en: "I would like to order a large coffee, please.", pt: "Eu gostaria de pedir um café grande, por favor." },
  { en: "Can I see the menu, please?", pt: "Posso ver o cardápio, por favor?" },
  { en: "Do you have any recommendations for dinner?", pt: "Você tem alguma recomendação para o jantar?" },
  { en: "I am allergic to peanuts and shellfish.", pt: "Sou alérgico a amendoim e frutos do mar." },
  { en: "I would like my steak cooked medium rare.", pt: "Eu gostaria do meu bife ao ponto para mal passado." },
  { en: "Could we get some more water for the table?", pt: "Poderia nos trazer mais água para a mesa?" },
  { en: "This meal is absolutely delicious!", pt: "Esta refeição está absolutamente deliciosa!" },
  { en: "Can we get the check, please?", pt: "Pode trazer a conta, por favor?" },
  { en: "Do you accept credit cards or only cash?", pt: "Vocês aceitam cartão de crédito ou só dinheiro?" },
  { en: "Let's split the bill down the middle.", pt: "Vamos dividir a conta no meio." },
  { en: "Could I get a box to take this home?", pt: "Você poderia me arrumar uma embalagem para levar para casa?" },
  { en: "A table for two, please.", pt: "Uma mesa para dois, por favor." },
  { en: "We have a reservation under the name John.", pt: "Temos uma reserva no nome de John." },
  { en: "What is the soup of the day?", pt: "Qual é a sopa do dia?" },
  { en: "Do you have any vegetarian options?", pt: "Vocês têm alguma opção vegetariana?" },
  { en: "Could I have the dressing on the side?", pt: "Você poderia trazer o molho à parte?" },
  { en: "The food is a bit too spicy for me.", pt: "A comida está um pouco apimentada demais para mim." },
  { en: "Everything was wonderful, thank you.", pt: "Estava tudo maravilhoso, obrigado." },
  { en: "Could you bring some extra napkins?", pt: "Você poderia trazer alguns guardanapos extras?" },
  { en: "We are ready to order now.", pt: "Estamos prontos para pedir agora." },
  { en: "I think there is a mistake on the bill.", pt: "Acho que há um erro na conta." },
  { en: "Can I get a refill on my drink?", pt: "Posso pedir refil da minha bebida?" },
  { en: "What kind of desserts do you have?", pt: "Que tipo de sobremesas vocês têm?" },
  { en: "I am full, I couldn't eat another bite.", pt: "Estou cheio, não conseguiria comer mais nada." },

  // --- BUSINESS & WORK ---
  { en: "Could you please send me the report by Friday?", pt: "Você poderia me enviar o relatório até sexta-feira?" },
  { en: "Let's schedule a meeting for next week.", pt: "Vamos agendar uma reunião para a semana que vem." },
  { en: "What are our main goals for this quarter?", pt: "Quais são nossos principais objetivos para este trimestre?" },
  { en: "Thank you for your time and consideration.", pt: "Obrigado pelo seu tempo e consideração." },
  { en: "I look forward to hearing from you soon.", pt: "Espero ouvir de você em breve." },
  { en: "Please let me know if you have any questions.", pt: "Por favor, me avise se você tiver alguma dúvida." },
  { en: "We need to improve our customer service.", pt: "Precisamos melhorar nosso atendimento ao cliente." },
  { en: "Can we discuss this over lunch?", pt: "Podemos discutir isso no almoço?" },
  { en: "I will follow up with you tomorrow morning.", pt: "Entrarei em contato com você amanhã de manhã." },
  { en: "That is a very interesting perspective.", pt: "Essa é uma perspectiva muito interessante." },
  { en: "We are currently working on a new project.", pt: "Atualmente estamos trabalhando em um novo projeto." },
  { en: "Please send the invoice directly to my email.", pt: "Por favor, envie a fatura diretamente para o meu e-mail." },
  { en: "I am calling regarding our appointment.", pt: "Estou ligando sobre o nosso compromisso." },
  { en: "Let's touch base next Monday afternoon.", pt: "Vamos nos falar na próxima segunda à tarde." },
  { en: "We need to find a solution to this problem.", pt: "Precisamos encontrar uma solução para este problema." },
  { en: "I have a lot of experience in this specific field.", pt: "Tenho muita experiência nesta área específica." },
  { en: "Please CC me on that email.", pt: "Por favor, me coloque em cópia nesse e-mail." },
  { en: "We need to brainstorm some new ideas.", pt: "Precisamos debater algumas ideias novas." },
  { en: "Can you give me an update on the project?", pt: "Você pode me dar uma atualização sobre o projeto?" },
  { en: "Let's schedule a video call for tomorrow.", pt: "Vamos agendar uma videochamada para amanhã." },
  { en: "The meeting has been postponed.", pt: "A reunião foi adiada." },
  { en: "I will be out of the office next week.", pt: "Estarei fora do escritório na próxima semana." },
  { en: "Who is in charge of this department?", pt: "Quem é o responsável por este departamento?" },
  { en: "Please review the attached document.", pt: "Por favor, revise o documento em anexo." },
  { en: "I am confident we can meet the deadline.", pt: "Estou confiante de que podemos cumprir o prazo." },
  { en: "We need to cut down on our expenses.", pt: "Precisamos cortar nossas despesas." },
  { en: "Let's get straight to the point.", pt: "Vamos direto ao ponto." },
  { en: "That sounds like a win-win situation.", pt: "Isso parece uma situação em que todos ganham." },
  { en: "I appreciate your hard work on this.", pt: "Agradeço seu trabalho duro nisso." },
  { en: "Could you clarify your last point?", pt: "Você poderia esclarecer seu último ponto?" },
  { en: "I need you to sign these papers.", pt: "Preciso que você assine estes papéis." },
  { en: "Can you share your screen with the team?", pt: "Você pode compartilhar sua tela com a equipe?" },
  { en: "You are on mute, we can't hear you.", pt: "Você está no mudo, não conseguimos te ouvir." },

  // --- SHOPPING & MONEY ---
  { en: "How much does this item cost?", pt: "Quanto custa este item?" },
  { en: "Do you have this in a different color?", pt: "Você tem isso em uma cor diferente?" },
  { en: "Can I try this on in the fitting room?", pt: "Posso provar isso no provador?" },
  { en: "Do you have a smaller size available?", pt: "Você tem um tamanho menor disponível?" },
  { en: "I am just looking right now, thank you.", pt: "Estou só dando uma olhadinha agora, obrigado." },
  { en: "What time does the store close tonight?", pt: "A que horas a loja fecha hoje à noite?" },
  { en: "I would like to return this shirt, please.", pt: "Gostaria de devolver esta camisa, por favor." },
  { en: "Do I need the original receipt for a refund?", pt: "Preciso do recibo original para ter o reembolso?" },
  { en: "Where is the nearest ATM machine?", pt: "Onde fica o caixa eletrônico mais próximo?" },
  { en: "Where are the fitting rooms?", pt: "Onde ficam os provadores?" },
  { en: "I am looking for a pair of black shoes.", pt: "Estou procurando um par de sapatos pretos." },
  { en: "Does this come with a warranty?", pt: "Isso vem com garantia?" },
  { en: "Do you offer a student discount?", pt: "Vocês oferecem desconto para estudantes?" },
  { en: "I think I will leave it, thanks.", pt: "Acho que vou deixar, obrigado." },
  { en: "Could you wrap this as a gift?", pt: "Você poderia embrulhar para presente?" },
  { en: "What is the exchange rate today?", pt: "Qual é a taxa de câmbio de hoje?" },
  { en: "My credit card was declined.", pt: "Meu cartão de crédito foi recusado." },
  { en: "I need to withdraw some cash.", pt: "Preciso sacar um pouco de dinheiro." },
  { en: "I am on a tight budget right now.", pt: "Estou com o orçamento apertado no momento." },
  { en: "This is a really good bargain.", pt: "Esta é uma ótima pechincha." },
  { en: "It is way too expensive.", pt: "Está caro demais." },

  // --- HEALTH & EMERGENCIES ---
  { en: "I am not feeling very well today.", pt: "Não estou me sentindo muito bem hoje." },
  { en: "I'm feeling a bit under the weather", pt: "Estou me sentindo um pouco mal." },
  { en: "I've caught a cold", pt: "Peguei um resfriado." },
  { en: "I'm feeling great", pt: "Estou me sentindo ótimo." },
  { en: "I'm feeling like a million dollars!", pt: "Estou me sentindo excelente!" },
  { en: "Do you need help?", pt: "Você precisa de ajuda?" },
  { en: "She needs to call the police", pt: "Ela precisa ligar para a polícia." },
  { en: "They are lost", pt: "Eles estão perdidos." },
  { en: "We need to have our car fixed", pt: "Precisamos mandar consertar o nosso carro." },
  { en: "I have a terrible headache and a fever.", pt: "Estou com uma dor de cabeça terrível e febre." },
  { en: "I need to see a doctor as soon as possible.", pt: "Preciso ver um médico o mais rápido possível." },
  { en: "Can you call an ambulance, please?", pt: "Você pode chamar uma ambulância, por favor?" },
  { en: "My wallet was stolen this morning.", pt: "Minha carteira foi roubada esta manhã." },
  { en: "I need to contact the police immediately.", pt: "Preciso entrar em contato com a polícia imediatamente." },
  { en: "Where is the nearest hospital?", pt: "Onde fica o hospital mais próximo?" },
  { en: "I lost my passport at the airport.", pt: "Perdi meu passaporte no aeroporto." },
  { en: "I have a pain in my lower back.", pt: "Tenho uma dor na lombar." },
  { en: "I feel dizzy and nauseous.", pt: "Me sinto tonto e enjoado." },
  { en: "Are you allergic to any medications?", pt: "Você é alérgico a algum medicamento?" },
  { en: "Please take a deep breath.", pt: "Por favor, respire fundo." },
  { en: "I need to make an appointment with the dentist.", pt: "Preciso marcar uma consulta com o dentista." },
  { en: "Help! Call the police!", pt: "Socorro! Chamem a polícia!" },
  { en: "Is there a pharmacy open late?", pt: "Tem alguma farmácia aberta até tarde?" },
  { en: "I need something for a sore throat.", pt: "Preciso de algo para dor de garganta." },
  { en: "I think I might have a fever.", pt: "Acho que posso estar com febre." },
  { en: "Where is the emergency exit?", pt: "Onde fica a saída de emergência?" },
  { en: "Please stay calm and wait for help.", pt: "Por favor, mantenha a calma e espere por ajuda." },

  // --- DAILY ROUTINE & HOME ---
  { en: "I usually wake up at seven o'clock.", pt: "Eu costumo acordar às sete em ponto." },
  { en: "I need to go to the grocery store after work.", pt: "Preciso ir ao supermercado depois do trabalho." },
  { en: "Can you pass me the salt and pepper, please?", pt: "Você pode me passar o sal e a pimenta, por favor?" },
  { en: "I am going to take a quick shower.", pt: "Vou tomar um banho rápido." },
  { en: "I need to do the laundry this weekend.", pt: "Preciso lavar a roupa neste fim de semana." },
  { en: "Let's stay in and watch a movie tonight.", pt: "Vamos ficar em casa e assistir a um filme hoje à noite." },
  { en: "I am feeling a little bit tired today.", pt: "Estou me sentindo um pouco cansado hoje." },
  { en: "Did you remember to lock the front door?", pt: "Você lembrou de trancar a porta da frente?" },
  { en: "I forgot my keys inside the house.", pt: "Esqueci minhas chaves dentro de casa." },
  { en: "Can you turn the volume down a little bit?", pt: "Você pode abaixar um pouco o volume?" },
  { en: "I am going to bed early tonight.", pt: "Vou para a cama cedo hoje." },
  { en: "Let's order some takeout for dinner.", pt: "Vamos pedir comida para o jantar." },
  { en: "I haven't done the dishes yet.", pt: "Eu ainda não lavei a louça." },
  { en: "Can you take out the trash?", pt: "Você pode levar o lixo para fora?" },
  { en: "The washing machine is broken.", pt: "A máquina de lavar está quebrada." },
  { en: "I need to sweep the floor.", pt: "Preciso varrer o chão." },
  { en: "I am going to walk the dog.", pt: "Vou passear com o cachorro." },
  { en: "What time do you usually go to bed?", pt: "A que horas você costuma ir para a cama?" },
  { en: "Did you feed the cat?", pt: "Você alimentou o gato?" },
  { en: "The sink is leaking.", pt: "A pia está vazando." },
  { en: "Let's open the windows to get some fresh air.", pt: "Vamos abrir as janelas para entrar um ar fresco." },
  { en: "I am going to water the plants.", pt: "Vou regar as plantas." },
  { en: "Turn off the lights when you leave.", pt: "Apague as luzes quando sair." },
  { en: "I have a lot of chores to do today.", pt: "Tenho muitas tarefas para fazer hoje." },

  // --- TECHNOLOGY & INTERNET ---
  { en: "My phone battery is almost completely dead.", pt: "A bateria do meu celular está quase acabando." },
  { en: "Do you have a charger I could borrow?", pt: "Você tem um carregador que possa me emprestar?" },
  { en: "What is the password for the Wi-Fi?", pt: "Qual é a senha do Wi-Fi?" },
  { en: "The Wi-Fi is really slow today.", pt: "O Wi-Fi está muito lento hoje." },
  { en: "My computer just crashed.", pt: "Meu computador acabou de travar." },
  { en: "I need to restart my router.", pt: "Preciso reiniciar meu roteador." },
  { en: "Can you text me the address?", pt: "Você pode me mandar o endereço por mensagem?" },
  { en: "Let's take a selfie!", pt: "Vamos tirar uma selfie!" },
  { en: "My inbox is completely full.", pt: "Minha caixa de entrada está completamente cheia." },
  { en: "I forgot my password again.", pt: "Esqueci minha senha de novo." },
  { en: "Please click the link in the description.", pt: "Por favor, clique no link na descrição." },
  { en: "The app keeps freezing.", pt: "O aplicativo não para de travar." },
  { en: "I will forward you the message.", pt: "Vou te encaminhar a mensagem." }
];
