// src/phraseBank.js

export const curatedWords = [
  // Common tricky pronunciations
  "Comfortable", "Vegetable", "Chocolate", "Temperature", "Schedule", 
  "Architecture", "Literature", "Development", "Opportunity", "Experience",
  "Important", "Restaurant", "Airport", "Appointment", "Tomorrow",
  "Yesterday", "Breakfast", "Language", "Vocabulary", "Pronunciation",
  "Squirrel", "Colonel", "Rural", "Thorough", "Throughout", 
  "Wednesday", "February", "Receipt", "Debt", "Doubt", 
  "Chaos", "Island", "Muscle", "Scissors", "Stomach", 
  "Headache", "Cough", "Hiccup", "Enough", "Recipe", 
  "Clothes", "Month", "Jewelry", "Iron", "Choir", 
  "Epitome", "Hyperbole", "Mischievous", "Nausea", "Syllable",

  // Business & Work
  "Knowledge", "Challenge", "Successful", "Environment", "Strategy",
  "Customer", "Manager", "Colleague", "Meeting", "Available",
  "Recommend", "Information", "Communication", "Organization", "Technology",
  "University", "Government", "Community", "International", "Difference",
  "Advantage", "Disadvantage", "Advertisement", "Agreement", "Signature", 
  "Contract", "Negotiate", "Profit", "Revenue", "Budget", 
  "Expense", "Investment", "Performance", "Presentation", "Procedure", 
  "Requirement", "Responsibility", "Solution", "Supervisor", "Department", 
  "Interview", "Resume", "Employee", "Employer", "Salary", 
  "Promotion", "Deadline", "Objective", "Analysis", "Feedback",

  // Adjectives, Adverbs & Everyday Nouns
  "Interesting", "Beautiful", "Dangerous", "Congratulations", "Appreciate",
  "Unfortunately", "Especially", "Immediately", "Absolutely", "Definitely",
  "Understand", "Remember", "Question", "Answer", "Business",
  "Decision", "Education", "Quality", "Service", "Product",
  "Incredible", "Fantastic", "Terrible", "Awesome", "Awful", 
  "Brilliant", "Excellent", "Generous", "Honest", "Patient", 
  "Reliable", "Serious", "Sincere", "Specific", "Typical", 
  "Unusual", "Valuable", "Vulnerable", "Wealthy", "Weird", 
  "Exactly", "Actually", "Basically", "Literally", "Probably", 
  "Quickly", "Rarely", "Suddenly", "Usually", "Destination", 
  "Itinerary", "Passenger", "Passport", "Reservation", "Accommodation", 
  "Excursion", "Sightseeing", "Transportation", "Vehicle", "Neighbor", 
  "Neighborhood", "Apartment", "Furniture", "Appliance", "Medicine", 
  "Prescription", "Symptom", "Treatment", "Vaccine", "Entertainment"
];

export const curatedPhrases = [
  // --- GREETINGS & SMALL TALK ---
  "Hello, how are you doing today?",
  "It is really nice to finally meet you.",
  "How has your day been so far?",
  "I am doing great, thank you for asking.",
  "What do you like to do in your free time?",
  "I am really looking forward to the weekend.",
  "Did you have a good weekend?",
  "The weather is absolutely beautiful today.",
  "It is supposed to rain tomorrow afternoon.",
  "I completely agree with your point of view.",
  "That sounds like a really great idea.",
  "I am sorry, I didn't quite catch that.",
  "Could you please repeat that a little slower?",
  "Thank you so much for all your help.",
  "You are very welcome, anytime.",
  "Long time no see! How have you been?",
  "What have you been up to lately?",
  "It has been a while since we last spoke.",
  "How is your family doing?",
  "Let's catch up sometime next week.",
  "Are you doing anything special this weekend?",
  "I really love your outfit today.",
  "That is so funny! I can't believe it.",
  "I am not sure what you mean.",
  "Could you explain that again?",
  "Have a great rest of your day!",
  "See you later, take care of yourself.",

  // --- TRAVEL & DIRECTIONS ---
  "Excuse me, where is the nearest subway station?",
  "How do I get to the airport from here?",
  "I need to buy a ticket to New York.",
  "What time does the next train leave?",
  "Is there a public restroom around here?",
  "I am looking for a pharmacy.",
  "Could you show me where that is on the map?",
  "How much does a taxi to the hotel cost?",
  "I need to book a room for two nights.",
  "What time is check-in and check-out?",
  "Can you help me carry my luggage?",
  "My flight is delayed by two hours.",
  "Where is the baggage claim area?",
  "Do I need to transfer to another terminal?",
  "Does this bus go to the city center?",
  "Could you tell me when to get off?",
  "I think we might be lost.",
  "Can you point me in the right direction?",
  "How far is it from here?",
  "Is it within walking distance?",
  "I would like to rent a car for three days.",
  "Where can I find a currency exchange?",
  "Do you know a good place to buy souvenirs?",
  "I need a window seat, please.",
  "Can I bring this on the airplane?",
  "What gate does the flight leave from?",
  "The traffic is really bad today.",

  // --- RESTAURANT & FOOD ---
  "I would like to order a large coffee, please.",
  "Can I see the menu, please?",
  "Do you have any recommendations for dinner?",
  "I am allergic to peanuts and shellfish.",
  "I would like my steak cooked medium rare.",
  "Could we get some more water for the table?",
  "This meal is absolutely delicious!",
  "Can we get the check, please?",
  "Do you accept credit cards or only cash?",
  "Let's split the bill down the middle.",
  "Could I get a box to take this home?",
  "A table for two, please.",
  "We have a reservation under the name John.",
  "What is the soup of the day?",
  "Do you have any vegetarian options?",
  "Could I have the dressing on the side?",
  "The food is a bit too spicy for me.",
  "Everything was wonderful, thank you.",
  "Could you bring some extra napkins?",
  "We are ready to order now.",
  "I think there is a mistake on the bill.",
  "Can I get a refill on my drink?",
  "What kind of desserts do you have?",
  "I am full, I couldn't eat another bite.",

  // --- BUSINESS & WORK ---
  "Could you please send me the report by Friday?",
  "Let's schedule a meeting for next week.",
  "What are our main goals for this quarter?",
  "Thank you for your time and consideration.",
  "I look forward to hearing from you soon.",
  "Please let me know if you have any questions.",
  "We need to improve our customer service.",
  "Can we discuss this over lunch?",
  "I will follow up with you tomorrow morning.",
  "That is a very interesting perspective.",
  "We are currently working on a new project.",
  "Please send the invoice directly to my email.",
  "I am calling regarding our appointment.",
  "Let's touch base next Monday afternoon.",
  "We need to find a solution to this problem.",
  "I have a lot of experience in this specific field.",
  "Please CC me on that email.",
  "We need to brainstorm some new ideas.",
  "Can you give me an update on the project?",
  "Let's schedule a video call for tomorrow.",
  "The meeting has been postponed.",
  "I will be out of the office next week.",
  "Who is in charge of this department?",
  "Please review the attached document.",
  "I am confident we can meet the deadline.",
  "We need to cut down on our expenses.",
  "Let's get straight to the point.",
  "That sounds like a win-win situation.",
  "I appreciate your hard work on this.",
  "Could you clarify your last point?",
  "I need you to sign these papers.",
  "Can you share your screen with the team?",
  "You are on mute, we can't hear you.",

  // --- SHOPPING & MONEY ---
  "How much does this item cost?",
  "Do you have this in a different color?",
  "Can I try this on in the fitting room?",
  "Do you have a smaller size available?",
  "I am just looking right now, thank you.",
  "What time does the store close tonight?",
  "I would like to return this shirt, please.",
  "Do I need the original receipt for a refund?",
  "Where is the nearest ATM machine?",
  "Where are the fitting rooms?",
  "I am looking for a pair of black shoes.",
  "Does this come with a warranty?",
  "Do you offer a student discount?",
  "I think I will leave it, thanks.",
  "Could you wrap this as a gift?",
  "What is the exchange rate today?",
  "My credit card was declined.",
  "I need to withdraw some cash.",
  "I am on a tight budget right now.",
  "This is a really good bargain.",
  "It is way too expensive.",

  // --- HEALTH & EMERGENCIES ---
  "I am not feeling very well today.",
  "I have a terrible headache and a fever.",
  "I need to see a doctor as soon as possible.",
  "Can you call an ambulance, please?",
  "My wallet was stolen this morning.",
  "I need to contact the police immediately.",
  "Where is the nearest hospital?",
  "I lost my passport at the airport.",
  "I have a pain in my lower back.",
  "I feel dizzy and nauseous.",
  "Are you allergic to any medications?",
  "Please take a deep breath.",
  "I need to make an appointment with the dentist.",
  "Help! Call the police!",
  "Is there a pharmacy open late?",
  "I need something for a sore throat.",
  "I think I might have a fever.",
  "Where is the emergency exit?",
  "Please stay calm and wait for help.",

  // --- DAILY ROUTINE & HOME ---
  "I usually wake up at seven o'clock.",
  "I need to go to the grocery store after work.",
  "Can you pass me the salt and pepper, please?",
  "I am going to take a quick shower.",
  "I need to do the laundry this weekend.",
  "Let's stay in and watch a movie tonight.",
  "I am feeling a little bit tired today.",
  "Did you remember to lock the front door?",
  "I forgot my keys inside the house.",
  "Can you turn the volume down a little bit?",
  "I am going to bed early tonight.",
  "Let's order some takeout for dinner.",
  "I haven't done the dishes yet.",
  "Can you take out the trash?",
  "The washing machine is broken.",
  "I need to sweep the floor.",
  "I am going to walk the dog.",
  "What time do you usually go to bed?",
  "Did you feed the cat?",
  "The sink is leaking.",
  "Let's open the windows to get some fresh air.",
  "I am going to water the plants.",
  "Turn off the lights when you leave.",
  "I have a lot of chores to do today.",

  // --- TECHNOLOGY & INTERNET ---
  "My phone battery is almost completely dead.",
  "Do you have a charger I could borrow?",
  "What is the password for the Wi-Fi?",
  "The Wi-Fi is really slow today.",
  "My computer just crashed.",
  "I need to restart my router.",
  "Can you text me the address?",
  "Let's take a selfie!",
  "My inbox is completely full.",
  "I forgot my password again.",
  "Please click the link in the description.",
  "The app keeps freezing.",
  "I will forward you the message."
];
